package cn.hc.domain;

/**
 * this class is generated by a tool, please DO NOT modify.
 * generated at 2017-07-09 18:59:53
 */
public class Resource {
    public static final String RESOURCES = "resources";
    public static final String ID = "id";
    public static final String TYPE = "type";
    public static final String MIME_TYPE = "mime_type";
    public static final String REFERENCE_ID = "reference_id";
    public static final String NAME = "name";
    public static final String ORIGINAL_FILE_NAME = "original_file_name";
    public static final String DESCRIPTION = "description";
    public static final String EXTENSION = "extension";
    public static final String STORAGE_TYPE = "storage_type";
    public static final String STORAGE_PARAM = "storage_param";
    public static final String SIZE = "size";
    public static final String ORIGINAL_HEIGHT = "original_height";
    public static final String ORIGINAL_WIDTH = "original_width";
    public static final String CREATED_TIME = "created_time";

    private java.util.UUID id;
    private Integer type;
    private String mimeType;
    private java.util.UUID referenceId;
    private String name;
    private String originalFileName;
    private String description;
    private String extension;
    private String storageType;
    private String storageParam;
    private Integer size;
    private Integer originalHeight;
    private Integer originalWidth;
    private java.util.Date createdTime;
    private String url;

    public String getUrl() {
        return url;
    }
    public void setUrl(String url) {
        this.url = url;
    }
    public java.util.UUID getId() { return id;}
    public void setId(java.util.UUID id) { this.id = id; }
    public Integer getType() { return type;}
    public void setType(Integer type) { this.type = type; }
    public String getMimeType() { return mimeType;}
    public void setMimeType(String mimeType) { this.mimeType = mimeType; }
    public java.util.UUID getReferenceId() { return referenceId;}
    public void setReferenceId(java.util.UUID referenceId) { this.referenceId = referenceId; }
    public String getName() { return name;}
    public void setName(String name) { this.name = name; }
    public String getOriginalFileName() { return originalFileName;}
    public void setOriginalFileName(String originalFileName) { this.originalFileName = originalFileName; }
    public String getDescription() { return description;}
    public void setDescription(String description) { this.description = description; }
    public String getExtension() { return extension;}
    public void setExtension(String extension) { this.extension = extension; }
    public String getStorageType() { return storageType;}
    public void setStorageType(String storageType) { this.storageType = storageType; }
    public String getStorageParam() { return storageParam;}
    public void setStorageParam(String storageParam) { this.storageParam = storageParam; }
    public Integer getSize() { return size;}
    public void setSize(Integer size) { this.size = size; }
    public Integer getOriginalHeight() { return originalHeight;}
    public void setOriginalHeight(Integer originalHeight) { this.originalHeight = originalHeight; }
    public Integer getOriginalWidth() { return originalWidth;}
    public void setOriginalWidth(Integer originalWidth) { this.originalWidth = originalWidth; }
    public java.util.Date getCreatedTime() { return createdTime;}
    public void setCreatedTime(java.util.Date createdTime) { this.createdTime = createdTime; }


}